mcts:
  max_iterations: 20
  continuous_improvement: true
  initial_root_children: 3
  exploration_constant: 1.414
  max_debug_children: 3
  max_evolve_children: 3
  failure_offset: 0
  failure_penalty_weight: 0.5
  max_debug_depth: 5

tutorials:
  num_tutorial_retrievals: 5
  condense_tutorials: false
  max_num_tutorials: 5
  max_tutorial_length: 50000
  use_tutorial_summary: true
